steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/taskshare:$COMMIT_SHA', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/taskshare:$COMMIT_SHA']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'taskshare'
      - '--image'
      - 'gcr.io/$PROJECT_ID/taskshare:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'DATABASE_URL=${_DATABASE_URL},GOOGLE_CLIENT_ID=${_GOOGLE_CLIENT_ID},GOOGLE_CLIENT_SECRET=${_GOOGLE_CLIENT_SECRET},GOOGLE_WORKSPACE_DOMAIN=${_GOOGLE_WORKSPACE_DOMAIN},SESSION_SECRET=${_SESSION_SECRET}'

images:
  - 'gcr.io/$PROJECT_ID/taskshare:$COMMIT_SHA'

substitutions:
  _DATABASE_URL: # Will be provided during deployment
  _GOOGLE_CLIENT_ID: # Will be provided during deployment
  _GOOGLE_CLIENT_SECRET: # Will be provided during deployment
  _GOOGLE_WORKSPACE_DOMAIN: # Will be provided during deployment, optional
  _SESSION_SECRET: # Will be provided during deployment